### ISSUE TITLE
miunlock

### ISSUE THREAD

**Issue by xiaohuzz** [penn5/miunlock#2]
copypaste the data from your web browser here
No next step

**Comment by penn5** [comment]
explain.

**Comment by zainarbani** [comment]
@xiaohuzz 
login [here](https://account.xiaomi.com) then open [here](https://account.xiaomi.com/pass/serviceLogin?sid=unlockApi&_json=true&passive=true&hidden=false)

**Comment by zainarbani** [comment]
@penn5 
can you give me the example result json output ?
